name: Jekyll Build Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
        bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --url-ignore "/#.*/"
